### ISSUE TITLE
刷到之后下单过程里在finish_checout过程里报了这个错误，是下单失败了吗

### ISSUE THREAD

**Issue by suntaord** [ToolGallery/APEStoreAssistant#12]
<img width="776" alt="image" src="https://github.com/ToolGallery/APEStoreAssistant/assets/127281180/f13f05a5-94a8-4227-af4e-23ebd7fe9e4d">

**Comment by FreeIdom** [comment]
到这步已经成功了，可以检查下邮件，这个问题我一直复现不了，后面优化下

**Comment by suntaord** [comment]
check了一下邮箱和短信，没有新消息，应该是失败了

**Comment by FreeIdom** [comment]
小改了下，再试试

**Comment by suntaord** [comment]
2023-09-22 10:37:18,431.431 INFO order - start_order: Order starting with 15-pro MU2W3CH/A 北京 北京...
2023-09-22 10:37:18,431.431 INFO order - add_to_cart: Adding to cart...
2023-09-22 10:37:19,592.592 INFO order - get_cart_item_id: Getting cart id...
2023-09-22 10:37:21,406.406 INFO order - start_checkout: Starting checkout...
2023-09-22 10:37:27,775.775 INFO order - fill_address: Starting fill address...
2023-09-22 10:37:31,942.942 INFO order - get_select_window: Delivery information: 周六 13:15 – 13:30
2023-09-22 10:37:31,942.942 INFO order - fill_contact: Starting fill contact...
2023-09-22 10:37:33,990.990 INFO order - fill_recipient: Starting fill recipient...
2023-09-22 10:37:35,783.783 INFO order - fill_pay_method: Starting fill pay methods...
2023-09-22 10:37:38,529.529 INFO order - finish_checkout: Starting final checkout...

这个吧，以我今天下午自己抢的经验来看18s开始start_order, 35s 才结束，估计肯定是会被人抢走了

**Comment by suntaord** [comment]
2023-09-22 11:12:19,934.934 INFO order - add_to_cart: Adding to cart...
2023-09-22 11:12:20,547.547 INFO order - get_cart_item_id: Getting cart id...
2023-09-22 11:12:21,212.212 INFO order - start_checkout: Starting checkout...
2023-09-22 11:12:21,527.527 ERROR inventory_monitoring - start: Failed to retrieve inventory data with error: 
Traceback (most recent call last):
  File "/app/actions/inventory_monitoring.py", line 73, in start
    self.start_order(
  File "/app/actions/inventory_monitoring.py", line 91, in start_order
    order_result = self.order.start_order(data)
  File "/app/actions/order.py", line 41, in start_order
    signin_url, signin_params, secure_api_host = self.start_checkout(
  File "/app/actions/order.py", line 147, in start_checkout
    signin_url = resp_json["head"]["data"]["url"]
KeyError: 'data'
又有新的错误了

**Comment by FreeIdom** [comment]
可以暂时忽略，一般是下单过程中没货了或者什么原因，现在都没处理，应该还不太影响

**Comment by FreeIdom** [comment]
#16
