### ISSUE TITLE
order pool报错

### ISSUE THREAD

**Issue by rzjsbbbb** [ToolGallery/APEStoreAssistant#20]
一开始运行时是好的，每隔一分钟会提示一次avaliable session pool有3个，但是自从报了下面这一堆错之后就不再显示avaliable session pool了
````
2023-10-13 11:37:04,408.408 INFO OrderPool.order/handle_pool: Number of available order session pools: 3
2023-10-13 11:37:07,989.989 INFO MainThread.inventory_monitoring/start: 苏州 iPhone 15 Pro Max 256GB 原色钛金属 店内取货 暂无供应
2023-10-13 11:37:17,978.978 INFO MainThread.inventory_monitoring/start: 苏州 iPhone 15 Pro Max 256GB 原色钛金属 店内取货 暂无供应
2023-10-13 11:37:26,683.683 INFO MainThread.inventory_monitoring/start: 苏州 iPhone 15 Pro Max 256GB 原色钛金属 店内取货 暂无供应
2023-10-13 11:37:34,410.410 INFO OrderPool.order/handle_pool: Number of available order session pools: 0
2023-10-13 11:37:34,411.411 INFO OrderPool.order/add_to_cart: Adding to cart...
2023-10-13 11:37:35,332.332 INFO MainThread.inventory_monitoring/start: 苏州 iPhone 15 Pro Max 256GB 原色钛金属 店内取货 暂无供应
Exception in thread OrderPool:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.apple.com.cn', port=443): Max retries exceeded with url: /shop/buy-iphone/iphone-15?ams=0&product=MU2Q3CH/A&step=attach (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/actions/order.py", line 471, in handle_pool
    pool_data = self.new(order_data)
  File "/app/actions/order.py", line 479, in new
    order.init_order(order_data)
  File "/app/actions/order.py", line 36, in init_order
    self.add_to_cart(order_data.model, order_data.model_code)
  File "/app/actions/order.py", line 121, in add_to_cart
    resp = self.session.get(
  File "/app/libs/requests.py", line 36, in get
    return self.request(
  File "/app/libs/requests.py", line 27, in request
    return self.session.request(method, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.apple.com.cn', port=443): Max retries exceeded with url: /shop/buy-iphone/iphone-15?ams=0&product=MU2Q3CH/A&step=attach (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-10-13 11:37:43,966.966 INFO MainThread.inventory_monitoring/start: 苏州 iPhone 15 Pro Max 256GB 原色钛金属 店内取货 暂无供应
2023-10-13 11:37:53,118.118 INFO MainThread.inventory_monitoring/start: 苏州 iPhone 15 Pro Max 256GB 原色钛金属 店内取货 暂无供应
2023-10-13 11:38:02,917.917 INFO MainThread.inventory_monitoring/start: 苏州 iPhone 15 Pro Max 256GB 原色钛金属 店内取货 暂无供应
2023-10-13 11:38:11,511.511 INFO MainThread.inventory_monitoring/start: 苏州 iPhone 15 Pro Max 256GB 原色钛金属 店内取货 暂无供应
2023-10-13 11:38:20,700.700 INFO MainThread.inventory_monitoring/start: 苏州 iPhone 15 Pro Max 256GB 原色钛金属 店内取货 暂无供应
2023-10-13 11:38:30,326.326 INFO MainThread.inventory_monitoring/start: 苏州 iPhone 15 Pro Max 256GB 原色钛金属 店内取货 暂无供应
2023-10-13 11:38:38,992.992 INFO MainThread.inventory_monitoring/start: 苏州 iPhone 15 Pro Max 256GB 原色钛金属 店内取货 暂无供应`
```

**Comment by FreeIdom** [comment]
增加了错误后重试
